// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Repositories;

namespace Model.Migrations
{
    [DbContext(typeof(LeagueOfLegendsContext))]
    [Migration("20200805120220_Alle Champs")]
    partial class AlleChamps
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Entities.Champion", b =>
                {
                    b.Property<int>("ChampionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlueEssencePrice")
                        .HasColumnType("int");

                    b.Property<string>("ChampionNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("RiotPointPrice")
                        .HasColumnType("int");

                    b.HasKey("ChampionId");

                    b.ToTable("Champions");

                    b.HasData(
                        new
                        {
                            ChampionId = 1,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Aatrox",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 2,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Ahri",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 3,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Akali",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 4,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Alistar",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 5,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Amumu",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 6,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Anivia",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 7,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Annie",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 8,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Aphelios",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 9,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Ashe",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 10,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Aurelion Sol",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 11,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Azir",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 12,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Bard",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 13,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Blitzcrank",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 14,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Brand",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 15,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Braum",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 16,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Caitlyn",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 17,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Camille",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 18,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Cassiopeia",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 19,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Cho'Gath",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 20,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Corki",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 21,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Darius",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 22,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Diana",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 23,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Draven",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 24,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Dr. Mundo",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 25,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Ekko",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 26,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Elise",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 27,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Evelynn",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 28,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Ezreal",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 29,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Fiddlesticks",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 30,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Fiora",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 31,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Fizz",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 32,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Galio",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 33,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Gangplank",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 34,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Garen",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 35,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Gnar",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 36,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Gragas",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 37,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Graves",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 38,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Hecarim",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 39,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Heimerdinger",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 40,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Illaoi",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 41,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Irelia",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 42,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Ivern",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 43,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Janna",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 44,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Jarvan IV",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 45,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Jax",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 46,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Jayce",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 47,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Jhin",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 48,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Jinx",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 49,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Kai'Sa",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 50,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Kalista",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 51,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Karma",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 52,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Karthus",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 53,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Kassadin",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 54,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Katarina",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 55,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Kayle",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 56,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Kayn",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 57,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Kennen",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 58,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Kha'Zix",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 59,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Kindred",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 60,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Kled",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 61,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Kog'Maw",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 62,
                            BlueEssencePrice = 0,
                            ChampionNaam = "LeBlanc",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 63,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Lee Sin",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 64,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Leona",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 65,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Lillia",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 66,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Lissandra",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 67,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Lucian",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 68,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Lulu",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 69,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Lux",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 70,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Malphite",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 71,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Malzahar",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 72,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Maokai",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 73,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Master Yi",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 74,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Miss Fortune",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 75,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Mordekaiser",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 76,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Morgana",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 77,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Nami",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 78,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Nasus",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 79,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Nautilus",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 80,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Neeko",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 81,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Nidalee",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 82,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Nocturne",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 83,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Nunu & Willump",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 84,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Olaf",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 85,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Orianna",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 86,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Ornn",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 87,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Pantheon",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 88,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Poppy",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 89,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Pyke",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 90,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Qiyana",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 91,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Quinn",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 92,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Rakan",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 93,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Rammus",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 94,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Rek'Sai",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 95,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Renekton",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 96,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Rengar",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 97,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Riven",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 98,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Rumble",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 99,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Ryze",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 100,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Sejuani",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 101,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Senna",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 102,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Sett",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 103,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Shaco",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 104,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Shen",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 105,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Shyvana",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 106,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Singed",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 107,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Sion",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 108,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Sivir",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 109,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Skarner",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 110,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Sona",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 111,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Soraka",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 112,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Swain",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 113,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Sylas",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 114,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Syndra",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 115,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Tahm Kench",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 116,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Taliyah",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 117,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Talon",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 118,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Taric",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 119,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Teemo",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 120,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Thresh",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 121,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Tristana",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 122,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Trundle",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 123,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Tryndamere",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 124,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Twisted Fate",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 125,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Twitch",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 126,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Udyr",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 127,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Urgot",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 128,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Varus",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 129,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Vayne",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 130,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Veigar",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 131,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Vel'Koz",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 132,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Vi",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 133,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Viktor",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 134,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Vladimir",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 135,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Volibear",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 136,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Warwick",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 137,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Wukong",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 138,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Xayah",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 139,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Xerath",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 140,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Xin Zhao",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 141,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Yasuo",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 142,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Yone",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 143,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Yorick",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 144,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Yuumi",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 145,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Zac",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 146,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Zed",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 147,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Ziggs",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 148,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Zilean",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 149,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Zoe",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 150,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Zyra",
                            RiotPointPrice = 0
                        });
                });

            modelBuilder.Entity("Model.Entities.Skin", b =>
                {
                    b.Property<int>("SkinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChampionId")
                        .HasColumnType("int");

                    b.Property<int>("RiotPointPrice")
                        .HasColumnType("int");

                    b.Property<string>("SkinNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("SkinId");

                    b.HasIndex("ChampionId");

                    b.ToTable("Skins");

                    b.HasData(
                        new
                        {
                            SkinId = 1,
                            ChampionId = 1,
                            RiotPointPrice = 975,
                            SkinNaam = "Justicar Aatrox"
                        },
                        new
                        {
                            SkinId = 2,
                            ChampionId = 1,
                            RiotPointPrice = 1350,
                            SkinNaam = "Mecha Aatrox"
                        },
                        new
                        {
                            SkinId = 3,
                            ChampionId = 1,
                            RiotPointPrice = 750,
                            SkinNaam = "Sea Hunter Aatrox"
                        },
                        new
                        {
                            SkinId = 4,
                            ChampionId = 1,
                            RiotPointPrice = 1350,
                            SkinNaam = "Blood Moon Aatrox"
                        },
                        new
                        {
                            SkinId = 5,
                            ChampionId = 1,
                            RiotPointPrice = 0,
                            SkinNaam = "Blood Moon Aatrox Prestige Edition"
                        },
                        new
                        {
                            SkinId = 6,
                            ChampionId = 1,
                            RiotPointPrice = 0,
                            SkinNaam = "Victorious Aatrox"
                        },
                        new
                        {
                            SkinId = 7,
                            ChampionId = 2,
                            RiotPointPrice = 975,
                            SkinNaam = "Dynasty Ahri"
                        },
                        new
                        {
                            SkinId = 8,
                            ChampionId = 2,
                            RiotPointPrice = 750,
                            SkinNaam = "Midnight Ahri"
                        },
                        new
                        {
                            SkinId = 9,
                            ChampionId = 2,
                            RiotPointPrice = 975,
                            SkinNaam = "Foxfire Ahri"
                        },
                        new
                        {
                            SkinId = 10,
                            ChampionId = 2,
                            RiotPointPrice = 975,
                            SkinNaam = "Popstar Ahri "
                        },
                        new
                        {
                            SkinId = 11,
                            ChampionId = 2,
                            RiotPointPrice = 0,
                            SkinNaam = "Challenger Ahri"
                        },
                        new
                        {
                            SkinId = 12,
                            ChampionId = 2,
                            RiotPointPrice = 750,
                            SkinNaam = "Academy Ahri"
                        },
                        new
                        {
                            SkinId = 13,
                            ChampionId = 2,
                            RiotPointPrice = 1350,
                            SkinNaam = "Arcade Ahri"
                        },
                        new
                        {
                            SkinId = 14,
                            ChampionId = 2,
                            RiotPointPrice = 1820,
                            SkinNaam = "Star Guardian Ahri"
                        },
                        new
                        {
                            SkinId = 15,
                            ChampionId = 2,
                            RiotPointPrice = 1350,
                            SkinNaam = "K/DA Ahri"
                        },
                        new
                        {
                            SkinId = 16,
                            ChampionId = 2,
                            RiotPointPrice = 0,
                            SkinNaam = "K/DA Ahri Prestige Edition"
                        },
                        new
                        {
                            SkinId = 17,
                            ChampionId = 2,
                            RiotPointPrice = 1350,
                            SkinNaam = "Elderwood Ahri"
                        });
                });

            modelBuilder.Entity("Model.Entities.Skin", b =>
                {
                    b.HasOne("Model.Entities.Champion", "Champion")
                        .WithMany("Skins")
                        .HasForeignKey("ChampionId")
                        .HasConstraintName("FK_Skin_Champion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
