// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Repositories;

namespace Model.Migrations
{
    [DbContext(typeof(LeagueOfLegendsContext))]
    [Migration("20200804212957_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Entities.Champion", b =>
                {
                    b.Property<int>("ChampionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlueEssencePrice")
                        .HasColumnType("int");

                    b.Property<string>("ChampionNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("RiotPointPrice")
                        .HasColumnType("int");

                    b.HasKey("ChampionId");

                    b.ToTable("Champions");

                    b.HasData(
                        new
                        {
                            ChampionId = 1,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Aatrox",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 2,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Ahri",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 3,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Akali",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 4,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Alistar",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 5,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Amumu",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 6,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Anivia",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 7,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Annie",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 8,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Aphelios",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 9,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Ashe",
                            RiotPointPrice = 0
                        },
                        new
                        {
                            ChampionId = 10,
                            BlueEssencePrice = 0,
                            ChampionNaam = "Aurelion Sol",
                            RiotPointPrice = 0
                        });
                });

            modelBuilder.Entity("Model.Entities.Skin", b =>
                {
                    b.Property<int>("SkinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChampionId")
                        .HasColumnType("int");

                    b.Property<int>("RiotPointPrice")
                        .HasColumnType("int");

                    b.Property<string>("SkinNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("SkinId");

                    b.HasIndex("ChampionId");

                    b.ToTable("Skins");

                    b.HasData(
                        new
                        {
                            SkinId = 1,
                            ChampionId = 1,
                            RiotPointPrice = 975,
                            SkinNaam = "Justicar Aatrox"
                        },
                        new
                        {
                            SkinId = 2,
                            ChampionId = 1,
                            RiotPointPrice = 1350,
                            SkinNaam = "Mecha Aatrox"
                        },
                        new
                        {
                            SkinId = 3,
                            ChampionId = 1,
                            RiotPointPrice = 750,
                            SkinNaam = "Sea Hunter Aatrox"
                        },
                        new
                        {
                            SkinId = 4,
                            ChampionId = 1,
                            RiotPointPrice = 1350,
                            SkinNaam = "Blood Moon Aatrox"
                        },
                        new
                        {
                            SkinId = 5,
                            ChampionId = 1,
                            RiotPointPrice = 0,
                            SkinNaam = "Blood Moon Aatrox Prestige Edition"
                        },
                        new
                        {
                            SkinId = 6,
                            ChampionId = 1,
                            RiotPointPrice = 0,
                            SkinNaam = "Victorious Aatrox"
                        },
                        new
                        {
                            SkinId = 7,
                            ChampionId = 2,
                            RiotPointPrice = 975,
                            SkinNaam = "Dynasty Ahri"
                        },
                        new
                        {
                            SkinId = 8,
                            ChampionId = 2,
                            RiotPointPrice = 750,
                            SkinNaam = "Midnight Ahri"
                        },
                        new
                        {
                            SkinId = 9,
                            ChampionId = 2,
                            RiotPointPrice = 975,
                            SkinNaam = "Foxfire Ahri"
                        },
                        new
                        {
                            SkinId = 10,
                            ChampionId = 2,
                            RiotPointPrice = 975,
                            SkinNaam = "Popstar Ahri "
                        },
                        new
                        {
                            SkinId = 11,
                            ChampionId = 2,
                            RiotPointPrice = 0,
                            SkinNaam = "Challenger Ahri"
                        },
                        new
                        {
                            SkinId = 12,
                            ChampionId = 2,
                            RiotPointPrice = 750,
                            SkinNaam = "Academy Ahri"
                        },
                        new
                        {
                            SkinId = 13,
                            ChampionId = 2,
                            RiotPointPrice = 1350,
                            SkinNaam = "Arcade Ahri"
                        },
                        new
                        {
                            SkinId = 14,
                            ChampionId = 2,
                            RiotPointPrice = 1820,
                            SkinNaam = "Star Guardian Ahri"
                        },
                        new
                        {
                            SkinId = 15,
                            ChampionId = 2,
                            RiotPointPrice = 1350,
                            SkinNaam = "K/DA Ahri"
                        },
                        new
                        {
                            SkinId = 16,
                            ChampionId = 2,
                            RiotPointPrice = 0,
                            SkinNaam = "K/DA Ahri Prestige Edition"
                        },
                        new
                        {
                            SkinId = 17,
                            ChampionId = 2,
                            RiotPointPrice = 1350,
                            SkinNaam = "Elderwood Ahri"
                        });
                });

            modelBuilder.Entity("Model.Entities.Skin", b =>
                {
                    b.HasOne("Model.Entities.Champion", "Champion")
                        .WithMany("Skins")
                        .HasForeignKey("ChampionId")
                        .HasConstraintName("FK_Skin_Champion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
